import type { MasterSection } from '@/types/library';

export type PantryCategoryKey = MasterSection;

export type PantryDefaultEntry = {
  ingredient: string;
  isDefault: boolean;
};

export const PANTRY_DEFAULTS: Record<PantryCategoryKey, PantryDefaultEntry[]> = {
  Seasonings: [
    { ingredient: 'Black Pepper', isDefault: true },
    { ingredient: 'Garlic Powder', isDefault: true },
    { ingredient: 'Onion Powder', isDefault: true },
    { ingredient: 'Paprika', isDefault: true },
    { ingredient: 'Salt', isDefault: true },
    { ingredient: 'Allspice', isDefault: false },
    { ingredient: 'Basil', isDefault: false },
    { ingredient: 'Brown Sugar', isDefault: false },
    { ingredient: 'Cajun Seasoning', isDefault: false },
    { ingredient: 'Cardamom', isDefault: false },
    { ingredient: 'Cayenne', isDefault: false },
    { ingredient: 'Chili Powder', isDefault: false },
    { ingredient: 'Cinnamon', isDefault: false },
    { ingredient: 'Cloves', isDefault: false },
    { ingredient: 'Coriander', isDefault: false },
    { ingredient: 'Cumin', isDefault: false },
    { ingredient: 'Curry Powder', isDefault: false },
    { ingredient: 'Garam Masala', isDefault: false },
    { ingredient: 'Ginger Powder', isDefault: false },
    { ingredient: 'Herbes de Provence', isDefault: false },
    { ingredient: 'Italian Seasoning', isDefault: false },
    { ingredient: 'Lemon Pepper', isDefault: false },
    { ingredient: 'Nutmeg', isDefault: false },
    { ingredient: 'Oregano', isDefault: false },
    { ingredient: 'Parsley', isDefault: false },
    { ingredient: 'Powdered Sugar', isDefault: false },
    { ingredient: 'Red Pepper Flakes', isDefault: false },
    { ingredient: 'Rosemary', isDefault: false },
    { ingredient: 'Smoked Paprika', isDefault: false },
    { ingredient: 'Steak Seasoning', isDefault: false },
    { ingredient: 'Thyme', isDefault: false },
    { ingredient: 'Turmeric', isDefault: false },
    { ingredient: 'Vanilla Extract', isDefault: false },
  ],
  Produce: [
    { ingredient: 'Bell Peppers', isDefault: true },
    { ingredient: 'Onions', isDefault: true },
    { ingredient: 'Potatoes', isDefault: true },
    { ingredient: 'Spinach', isDefault: true },
    { ingredient: 'Tomatoes', isDefault: true },
    { ingredient: 'Anaheim Pepper', isDefault: false },
    { ingredient: 'Apples', isDefault: false },
    { ingredient: 'Arugula', isDefault: false },
    { ingredient: 'Asparagus', isDefault: false },
    { ingredient: 'Avocado', isDefault: false },
    { ingredient: 'Banana Pepper', isDefault: false },
    { ingredient: 'Bananas', isDefault: false },
    { ingredient: 'Basil', isDefault: false },
    { ingredient: 'Blueberries', isDefault: false },
    { ingredient: 'Broccoli', isDefault: false },
    { ingredient: 'Brussels Sprouts', isDefault: false },
    { ingredient: 'Cabbage', isDefault: false },
    { ingredient: 'Carolina Reaper Pepper', isDefault: false },
    { ingredient: 'Carrots', isDefault: false },
    { ingredient: 'Cauliflower', isDefault: false },
    { ingredient: 'Celery', isDefault: false },
    { ingredient: 'Chili Pepper', isDefault: false },
    { ingredient: 'Chives', isDefault: false },
    { ingredient: 'Cilantro', isDefault: false },
    { ingredient: 'Corn', isDefault: false },
    { ingredient: 'Cucumbers', isDefault: false },
    { ingredient: 'Eggplant', isDefault: false },
    { ingredient: 'Garlic', isDefault: false },
    { ingredient: 'Ghost Pepper', isDefault: false },
    { ingredient: 'Ginger', isDefault: false },
    { ingredient: 'Green Beans', isDefault: false },
    { ingredient: 'Herbs', isDefault: false },
    { ingredient: 'Jalapeño Pepper', isDefault: false },
    { ingredient: 'Kale', isDefault: false },
    { ingredient: 'Lemons', isDefault: false },
    { ingredient: 'Lettuce', isDefault: false },
    { ingredient: 'Limes', isDefault: false },
    { ingredient: 'Mango', isDefault: false },
    { ingredient: 'Mushrooms', isDefault: false },
    { ingredient: 'Oranges', isDefault: false },
    { ingredient: 'Parsley', isDefault: false },
    { ingredient: 'Peas', isDefault: false },
    { ingredient: 'Pineapple', isDefault: false },
    { ingredient: 'Poblano Pepper', isDefault: false },
    { ingredient: 'Raspberries', isDefault: false },
    { ingredient: 'Rosemary', isDefault: false },
    { ingredient: 'Serrano Pepper', isDefault: false },
    { ingredient: 'Shallots', isDefault: false },
    { ingredient: 'Strawberries', isDefault: false },
    { ingredient: 'Sweet Potatoes', isDefault: false },
    { ingredient: 'Thyme', isDefault: false },
    { ingredient: 'Zucchini', isDefault: false },
  ],
  Proteins: [
    { ingredient: 'Bacon', isDefault: true },
    { ingredient: 'Chicken Breast', isDefault: true },
    { ingredient: 'Cod', isDefault: true },
    { ingredient: 'Eggs', isDefault: true },
    { ingredient: 'Ground Beef', isDefault: true },
    { ingredient: 'Salmon', isDefault: true },
    { ingredient: 'Black Beans', isDefault: false },
    { ingredient: 'Canadian Bacon', isDefault: false },
    { ingredient: 'Catfish', isDefault: false },
    { ingredient: 'Chickpeas', isDefault: false },
    { ingredient: 'Chorizo', isDefault: false },
    { ingredient: 'Crab Meat', isDefault: false },
    { ingredient: 'Duck Breast', isDefault: false },
    { ingredient: 'Edamame', isDefault: false },
    { ingredient: 'Flounder', isDefault: false },
    { ingredient: 'Greek Yogurt', isDefault: false },
    { ingredient: 'Ground Turkey', isDefault: false },
    { ingredient: 'Haddock', isDefault: false },
    { ingredient: 'Halibut', isDefault: false },
    { ingredient: 'Ham', isDefault: false },
    { ingredient: 'Lamb Chops', isDefault: false },
    { ingredient: 'Lentils', isDefault: false },
    { ingredient: 'Mahi Mahi', isDefault: false },
    { ingredient: 'Meatballs', isDefault: false },
    { ingredient: 'Pork Chops', isDefault: false },
    { ingredient: 'Prosciutto', isDefault: false },
    { ingredient: 'Protein Powder', isDefault: false },
    { ingredient: 'Red Snapper', isDefault: false },
    { ingredient: 'Roast Beef', isDefault: false },
    { ingredient: 'Rotisserie Chicken', isDefault: false },
    { ingredient: 'Sausage', isDefault: false },
    { ingredient: 'Scallops', isDefault: false },
    { ingredient: 'Shrimp', isDefault: false },
    { ingredient: 'Smoked Salmon', isDefault: false },
    { ingredient: 'Sole', isDefault: false },
    { ingredient: 'Steak', isDefault: false },
    { ingredient: 'Tempeh', isDefault: false },
    { ingredient: 'Tilapia', isDefault: false },
    { ingredient: 'Tofu', isDefault: false },
    { ingredient: 'Tuna', isDefault: false },
    { ingredient: 'Turkey Bacon', isDefault: false },
    { ingredient: 'Turkey Breast', isDefault: false },
    { ingredient: 'Turkey Sausage', isDefault: false },
    { ingredient: 'Turkey Slices', isDefault: false },
    { ingredient: 'Veggie Patty', isDefault: false },
    { ingredient: 'Venison', isDefault: false },
  ],
  Grains: [
    { ingredient: 'Rice', isDefault: true },
    { ingredient: 'Quinoa', isDefault: true },
    { ingredient: 'Barley', isDefault: true },
    { ingredient: 'Farro', isDefault: true },
    { ingredient: 'Millet', isDefault: true },
    { ingredient: 'Couscous', isDefault: true },
    { ingredient: 'Wild Rice', isDefault: false },
    { ingredient: 'Bulgur', isDefault: false },
    { ingredient: 'Freekeh', isDefault: false },
    { ingredient: 'Oats', isDefault: false },
    { ingredient: 'Polenta', isDefault: false },
    { ingredient: 'Orzo', isDefault: false },
  ],
  Breads: [
    { ingredient: 'Bun', isDefault: true },
    { ingredient: 'Tortillas', isDefault: true },
    { ingredient: 'White Bread', isDefault: true },
    { ingredient: 'Whole Grain Bread', isDefault: true },
    { ingredient: 'Wrap', isDefault: true },
    { ingredient: 'Bagels', isDefault: false },
    { ingredient: 'Baguette', isDefault: false },
    { ingredient: 'Biscuits', isDefault: false },
    { ingredient: 'Brioche', isDefault: false },
    { ingredient: 'Ciabatta', isDefault: false },
    { ingredient: 'Cinnamon Rolls', isDefault: false },
    { ingredient: 'Croissant', isDefault: false },
    { ingredient: 'Dinner Rolls', isDefault: false },
    { ingredient: 'English Muffins', isDefault: false },
    { ingredient: 'Flatbread', isDefault: false },
    { ingredient: 'Focaccia', isDefault: false },
    { ingredient: 'French Toast', isDefault: false },
    { ingredient: 'Garlic Bread', isDefault: false },
    { ingredient: 'Muffins', isDefault: false },
    { ingredient: 'Naan', isDefault: false },
    { ingredient: 'Pancake Mix', isDefault: false },
    { ingredient: 'Pita Bread', isDefault: false },
    { ingredient: 'Pretzel Bun', isDefault: false },
    { ingredient: 'Rye Bread', isDefault: false },
    { ingredient: 'Sourdough', isDefault: false },
    { ingredient: 'Toast', isDefault: false },
    { ingredient: 'Waffles', isDefault: false },
  ],
  Dairy: [
    { ingredient: 'Butter', isDefault: true },
    { ingredient: 'Cheddar', isDefault: true },
    { ingredient: 'Milk', isDefault: true },
    { ingredient: 'Mozzarella', isDefault: true },
    { ingredient: 'Yogurt', isDefault: true },
    { ingredient: 'American', isDefault: false },
    { ingredient: 'Blue Cheese', isDefault: false },
    { ingredient: 'Brie', isDefault: false },
    { ingredient: 'Colby Jack', isDefault: false },
    { ingredient: 'Condensed Milk', isDefault: false },
    { ingredient: 'Cream', isDefault: false },
    { ingredient: 'Cream Cheese', isDefault: false },
    { ingredient: 'Evaporated Milk', isDefault: false },
    { ingredient: 'Feta', isDefault: false },
    { ingredient: 'Goat Cheese', isDefault: false },
    { ingredient: 'Half and Half', isDefault: false },
    { ingredient: 'Heavy Cream', isDefault: false },
    { ingredient: 'Monterey Jack', isDefault: false },
    { ingredient: 'Parmesan', isDefault: false },
    { ingredient: 'Pepper Jack', isDefault: false },
    { ingredient: 'Provolone', isDefault: false },
    { ingredient: 'Ricotta', isDefault: false },
    { ingredient: 'Sour Cream', isDefault: false },
    { ingredient: 'Swiss', isDefault: false },
    { ingredient: 'Whipped Cream', isDefault: false },
  ],
  'Sauces/Condiments': [
    { ingredient: 'BBQ Sauce', isDefault: true },
    { ingredient: 'Ketchup', isDefault: true },
    { ingredient: 'Mayo', isDefault: true },
    { ingredient: 'Mustard', isDefault: true },
    { ingredient: 'Soy Sauce', isDefault: true },
    { ingredient: 'Aioli', isDefault: false },
    { ingredient: 'Balsamic Glaze', isDefault: false },
    { ingredient: 'Caesar Dressing', isDefault: false },
    { ingredient: 'Chili Garlic Sauce', isDefault: false },
    { ingredient: 'Chocolate Syrup', isDefault: false },
    { ingredient: 'Cocktail Sauce', isDefault: false },
    { ingredient: 'Fish Sauce', isDefault: false },
    { ingredient: 'Fruit Preserves', isDefault: false },
    { ingredient: 'Gravy', isDefault: false },
    { ingredient: 'Hoisin Sauce', isDefault: false },
    { ingredient: 'Hollandaise Sauce', isDefault: false },
    { ingredient: 'Honey', isDefault: false },
    { ingredient: 'Honey Mustard', isDefault: false },
    { ingredient: 'Hot Sauce', isDefault: false },
    { ingredient: 'Hummus', isDefault: false },
    { ingredient: 'Italian Dressing', isDefault: false },
    { ingredient: 'Maple Syrup', isDefault: false },
    { ingredient: 'Peanut Sauce', isDefault: false },
    { ingredient: 'Pesto', isDefault: false },
    { ingredient: 'Ponzu', isDefault: false },
    { ingredient: 'Ranch Dressing', isDefault: false },
    { ingredient: 'Salsa', isDefault: false },
    { ingredient: 'Sriracha', isDefault: false },
    { ingredient: 'Steak Sauce', isDefault: false },
    { ingredient: 'Strawberry Syrup', isDefault: false },
    { ingredient: 'Tahini', isDefault: false },
    { ingredient: 'Tartar Sauce', isDefault: false },
    { ingredient: 'Teriyaki Sauce', isDefault: false },
    { ingredient: 'Tzatziki', isDefault: false },
    { ingredient: 'Worcestershire Sauce', isDefault: false },
  ],
  'Non-Perishable Items': [
    { ingredient: 'Chicken Broth', isDefault: true },
    { ingredient: 'Flour', isDefault: true },
    { ingredient: 'Olive Oil', isDefault: true },
    { ingredient: 'Sugar', isDefault: true },
    { ingredient: 'Vinegar', isDefault: true },
    { ingredient: 'Almond Butter', isDefault: false },
    { ingredient: 'Apple Cider Vinegar', isDefault: false },
    { ingredient: 'Avocado Oil', isDefault: false },
    { ingredient: 'Balsamic Vinegar', isDefault: false },
    { ingredient: 'Beef Broth', isDefault: false },
    { ingredient: 'Breadcrumbs', isDefault: false },
    { ingredient: 'Canned Beans', isDefault: false },
    { ingredient: 'Canned Corn', isDefault: false },
    { ingredient: 'Canned Fruit', isDefault: false },
    { ingredient: 'Canned Salmon', isDefault: false },
    { ingredient: 'Canned Tomatoes', isDefault: false },
    { ingredient: 'Canned Tuna', isDefault: false },
    { ingredient: 'Canola Oil', isDefault: false },
    { ingredient: 'Cereal', isDefault: false },
    { ingredient: 'Coconut Milk', isDefault: false },
    { ingredient: 'Coffee Grounds', isDefault: false },
    { ingredient: 'Cooking Spray', isDefault: false },
    { ingredient: 'Croutons', isDefault: false },
    { ingredient: 'Crushed Tomatoes', isDefault: false },
    { ingredient: 'Distilled White Vinegar', isDefault: false },
    { ingredient: 'Granola', isDefault: false },
    { ingredient: 'Honey', isDefault: false },
    { ingredient: 'Jam', isDefault: false },
    { ingredient: 'Jelly', isDefault: false },
    { ingredient: 'Maple Syrup', isDefault: false },
    { ingredient: 'Nuts', isDefault: false },
    { ingredient: 'Panko Crumbs', isDefault: false },
    { ingredient: 'Peanut Butter', isDefault: false },
    { ingredient: 'Rice Wine Vinegar', isDefault: false },
    { ingredient: 'Stock Cubes', isDefault: false },
    { ingredient: 'Sweeteners', isDefault: false },
    { ingredient: 'Tea Bags', isDefault: false },
    { ingredient: 'Tomato Paste', isDefault: false },
    { ingredient: 'Trail Mix', isDefault: false },
    { ingredient: 'Vegetable Broth', isDefault: false },
    { ingredient: 'Vegetable Oil', isDefault: false },
  ],
  Pasta: [
    { ingredient: 'Spaghetti', isDefault: true },
    { ingredient: 'Penne', isDefault: true },
    { ingredient: 'Rotini', isDefault: true },
    { ingredient: 'Linguine', isDefault: true },
    { ingredient: 'Macaroni', isDefault: true },
    { ingredient: 'Angel Hair', isDefault: false },
    { ingredient: 'Bow Tie', isDefault: false },
    { ingredient: 'Couscous', isDefault: false },
    { ingredient: 'Fettuccine', isDefault: false },
    { ingredient: 'Lasagna Noodles', isDefault: false },
    { ingredient: 'Orzo', isDefault: false },
    { ingredient: 'Ramen', isDefault: false },
    { ingredient: 'Rice Noodles', isDefault: false },
    { ingredient: 'Rigatoni', isDefault: false },
    { ingredient: 'Shell Pasta', isDefault: false },
  ],
  Equipment: [
    { ingredient: 'Baking Sheet', isDefault: true },
    { ingredient: 'Knife', isDefault: true },
    { ingredient: 'Microwave', isDefault: true },
    { ingredient: 'Oven', isDefault: true },
    { ingredient: 'Skillet', isDefault: true },
    { ingredient: 'Air Fryer', isDefault: false },
    { ingredient: 'Baking Dish', isDefault: false },
    { ingredient: 'Blender', isDefault: false },
    { ingredient: 'Cutting Board', isDefault: false },
    { ingredient: 'Egg Ring', isDefault: false },
    { ingredient: 'Food Processor', isDefault: false },
    { ingredient: 'Frying Pan', isDefault: false },
    { ingredient: 'Griddle', isDefault: false },
    { ingredient: 'Grill', isDefault: false },
    { ingredient: 'Instant Pot', isDefault: false },
    { ingredient: 'Measuring Cups', isDefault: false },
    { ingredient: 'Mixing Bowl', isDefault: false },
    { ingredient: 'Roasting Pan', isDefault: false },
    { ingredient: 'Saucepan', isDefault: false },
    { ingredient: 'Slow Cooker', isDefault: false },
    { ingredient: 'Spatula', isDefault: false },
    { ingredient: 'Toaster', isDefault: false },
    { ingredient: 'Tongs', isDefault: false },
    { ingredient: 'Waffle Iron', isDefault: false },
    { ingredient: 'Whisk', isDefault: false },
  ],
};

export const getDefaultPantryItems = (section: MasterSection): string[] =>
  PANTRY_DEFAULTS[section]?.filter((entry) => entry.isDefault).map((entry) => entry.ingredient) ?? [];

export const getSuggestedPantryItems = (section: MasterSection): string[] =>
  PANTRY_DEFAULTS[section]?.map((entry) => entry.ingredient) ?? [];
