[build]
  command = "npx expo export --platform web"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/openai"
  to = "/.netlify/functions/openai-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
